apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: SonarQube
metadata:
  name: sonarqube
  namespace: example-env
spec:
  clusterName: example-cluster
  labels:
    team: platform
  values:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      requests:
        cpu: 400m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
